# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: danmaku.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

from typing import List

import betterproto


@dataclass(eq=False, repr=False)
class DanmakuElem(betterproto.Message):
    id: int = betterproto.int64_field(1)
    progress: int = betterproto.int32_field(2)
    mode: int = betterproto.int32_field(3)
    fontsize: int = betterproto.int32_field(4)
    color: int = betterproto.uint32_field(5)
    mid_hash: str = betterproto.string_field(6)
    content: str = betterproto.string_field(7)
    ctime: int = betterproto.int64_field(8)
    weight: int = betterproto.int32_field(9)
    action: str = betterproto.string_field(10)
    pool: int = betterproto.int32_field(11)
    dmid_str: str = betterproto.string_field(12)
    attr: int = betterproto.int32_field(13)


@dataclass(eq=False, repr=False)
class DanmakuSegment(betterproto.Message):
    elems: List[DanmakuElem] = betterproto.message_field(1)
